export const ordenesIniciales = [
  {
    id: 1,
    placa: 'KDU369',
    estado: 'entregado',
    fechaCreacion: '2026-01-15',
    lubricante: 'SI',
    valorLubricante: '28500',
    engraseFilGasolina: 'NO',
    valorEngraseFilGasolina: '',
    cajaTransmision: '',
    cambioAireAC: '',
    filtros: {
      fAire: 'WA9455',
      fAceite: 'PH3593A',
      fGasolina: '',
      fDiesel: '',
      aireAcon: '',
    },
    lubricantes: {
      lubMotor: { marca: 'MOTORLINE SAE 10w40', cantidad: '1/2 galón' },
      transCaja: { marca: '', cantidad: '' },
      adicionales: { marca: '', cantidad: '' },
    },
  },
  {
    id: 2,
    placa: 'KDU369',
    estado: 'en_proceso',
    fechaCreacion: '2026-05-10',
    lubricante: 'SI',
    valorLubricante: '18900',
    engraseFilGasolina: 'SI',
    valorEngraseFilGasolina: '11200_camioneta',
    cajaTransmision: '10500',
    cambioAireAC: '',
    filtros: {
      fAire: '',
      fAceite: 'PH3593A',
      fGasolina: 'GF457',
      fDiesel: '',
      aireAcon: '',
    },
    lubricantes: {
      lubMotor: { marca: 'MOTORLINE SAE 15w40', cantidad: '2 cuartos' },
      transCaja: { marca: 'ATF Dexron III', cantidad: '1 cuarto' },
      adicionales: { marca: '', cantidad: '' },
    },
  },
  {
    id: 3,
    placa: 'XYZ789',
    estado: 'recibido',
    fechaCreacion: '2026-05-18',
    lubricante: 'NO',
    valorLubricante: '',
    engraseFilGasolina: 'NO',
    valorEngraseFilGasolina: '',
    cajaTransmision: '',
    cambioAireAC: '5500',
    filtros: {
      fAire: '',
      fAceite: '',
      fGasolina: '',
      fDiesel: '',
      aireAcon: 'KIT-AC-01',
    },
    lubricantes: {
      lubMotor: { marca: '', cantidad: '' },
      transCaja: { marca: '', cantidad: '' },
      adicionales: { marca: '', cantidad: '' },
    },
  },
  {
    id: 4,
    placa: 'DEF456',
    estado: 'terminado',
    fechaCreacion: '2026-04-10',
    lubricante: 'SI',
    valorLubricante: '34700_especial',
    engraseFilGasolina: 'SI',
    valorEngraseFilGasolina: '22200_sencillo',
    cajaTransmision: '18900',
    cambioAireAC: '',
    filtros: {
      fAire: 'CA10165',
      fAceite: 'ML16170',
      fGasolina: 'GF301',
      fDiesel: '',
      aireAcon: '',
    },
    lubricantes: {
      lubMotor: { marca: 'MOTORLINE SAE 20w50', cantidad: '1 galon' },
      transCaja: { marca: 'Mercon V', cantidad: '1 cuarto' },
      adicionales: { marca: 'Refrigerante', cantidad: '1' },
    },
  },
];
